---
title: "VMS Main Text Figures"
author: "M Fisher"
date: "2023-03-07"
output: html_document
---
## Description

Create figures for main text


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(magrittr)
library(here)
library(raster)
library(adehabitatHR)
library(move)
library(pryr)
library(vegan)
library(cowplot)
library(plotrix)
library(janitor)
library(PNWColors)

source(here('R','getmode.R'))
```

User inputs
```{r}
keep_years <- seq(2013,2018)
```


## Data

Vessel length keys
```{r}
vlengths <- read_csv(here('project-dat','vessel_groups','length_key_dcrb_vms_vessels.csv'))
```

Clustering groups
```{r}
vgroups <- read_csv(here('project-dat','vessel_groups','k4_NaNspeedfilter_2014clusterYR_byArea_noncon-group-key.csv'))
```

Earth mover's distance (by vessel)
```{r}
emd.dat <- read_csv(here('project-dat','statistics','EMD_annual_per_vessel_90ud_75grid_2011-18crabYrs.csv'))
```
Earth mover's distance (means)
```{r}
emd_means <- read_csv(here('project-dat','statistics','meanEMD_annual_bysize_90ud_75grid.csv'))
emd_group_means <- read_csv(here('project-dat','statistics','meanEMD_annual_bygroup_90ud_75grid_k4_2014clusterYR.csv'))
```

Earth mover's distance (significance testing)
```{r}
load(here('project-dat','statistics','wilcox_tests_bylength.rds'))
```



BA index (by cluster)






## Figure 2




```{r}
plot.all <- ggplot(emd_means, aes(x=crab_years,y=mean.emd/1000)) +
  geom_point(size=2, aes(col=vessel_size,pch=vessel_size)) +
  geom_errorbar(aes(ymin=(mean.emd-sd.emd)/1000,ymax=(mean.emd+sd.emd)/1000,col=vessel_size,pch=vessel_size),width=0.25)+
  geom_text(data=sig.lengths.out, aes(x=crab_years,y=y,label=significance),size=10) +
  geom_vline(xintercept=1.5, size=2) +
  scale_color_manual(values=pnw_palette("Starfish",7)[c(1,4)]) +
  xlab("Crab Year Comparison") + ylab("Earth Mover's Distance (x1000)") +
  theme_bw() + theme(panel.grid.major.x=element_blank(),
                     panel.grid.minor.x=element_blank(),
                     axis.text.y=element_text(size=13),
                     axis.text.x=element_text(angle=90,hjust=1,vjust=0.5,size=14),
                     axis.title=element_text(size=16),
                     
                     legend.position="none")
plot.all
```
```{r}
plot.gr <- ggplot(emd_group_means, aes(x=crab_years,y=mean.emd/1000, col=`Vessel Size`,pch=`Vessel Size`)) +
  geom_point(size=2) +
  facet_wrap(~`Vessel Group`) +
  geom_errorbar(aes(ymin=(mean.emd-sd.emd)/1000,ymax=(mean.emd+sd.emd)/1000),width=0.25)+
  geom_vline(xintercept=1.5, size=2) +
  scale_color_manual(values=pnw_palette("Starfish",7)[c(1,4)]) +
  xlab("Crab Year Comparison") + ylab("") +
  theme_bw() + theme(panel.grid.major.x=element_blank(),
                     panel.grid.minor.x=element_blank(),
                     axis.text.x=element_text(angle=90,hjust=1,vjust=0.5,size=13),
                     axis.text.y=element_text(size=13),
                     strip.text=element_text(size=16),
                     axis.title=element_text(size=16),
                     legend.title=element_text(size=16),
                     legend.text=element_text(size=13))
plot.gr
```

```{r}
png(here::here('project-dat','figures',"2013-18_EMDmeans.png"),width=750,height=400)
plot_grid(plot.all,plot.gr,rel_widths=c(0.55,1),labels="auto")
dev.off()
```
<br>


## Supplement to Fig. 2: EMD Density per year
```{r}
sfig <- ggplot(emd.dat %>% filter(crab_years %in% emd_means$crab_years),aes(x=emd/1000,fill=crab_years)) +
  geom_density(alpha=.5) +
  facet_wrap(~vessel_size, scale="free_y") +
  scale_fill_manual(values=rev(pnw_palette("Moth",10)[1:5])) +
  xlab("Earth Mover's Distance (x1000)") + ylab("Density") +
  theme_bw() + theme(legend.position="none",panel.grid.minor=element_blank(),
                     axis.text.x=element_text(angle=90,hjust=1,vjust=0.5,size=10),
                     axis.title=element_text(size=14),
                     strip.text=element_text(size=14))
sfig
png(here::here('project-dat','figures',"supplement_2013-18_EMDdistributions.png"),width=600,height=400)
sfig
dev.off()
```

