---
title: "Mapping UDs"
author: "M. Fisher"
date: "4/2/2023"
output: html_document
---

## Description

Map utilization distributions


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(maps)
library(here)
library(rgdal)
library(rgeos)
library(grid); library(PNWColors)
```


User inputs
```{r}
keep_years <- seq(2013,2018)
k=5   # number of clusters
p=90  # % utilization distribution
kud_grid <- 75  # grid size

indir <- 'project-dat/vms/interpolation_60min/NaN_speed_filter/group90ud'


## change the resolution of the map figure
png_res = 200 # suggested:200
## offset of each coastline from the others; this should change with res
offset = 2.5  # suggested:2.5
## size of port group labels on maps; this should change with res
pg_label_size = 4  # suggested:4

```


## Data

Basemap
```{r}
data(stateMapEnv)
states_df <- map_data("state") %>%
  filter(region %in% c("california"))
states_df_sp <- states_df
coordinates(states_df_sp) <- c("long", "lat")
proj4string(states_df_sp) <- CRS("+init=epsg:4326") # WGS 84
# states_geo <- spTransform(states_df_sp, CRS("+init=epsg:32610"))
states_geo_df <- as.data.frame(states_df_sp)


states_df_coast <- filter(states_df,long < -116) %>%
  filter(!(long > -120 & lat > 32.5)) %>%
  filter(!(long > -122.5 & lat > 38.5))
```


port group points
```{r}
pg <- read.csv(here::here('project-dat','pcgroup_mean_coordinates.csv'))
pg$port_group <- c("Bodega Bay","Fort Bragg","Crescent City","Eureka","Monterey","Morro Bay","San Francisco")
coordinates(pg) <- c("Lon", "Lat")
proj4string(pg) <- CRS("+init=epsg:4326") # WGS 84
# pg_geo <- spTransform(pg, CRS("+init=epsg:32610"))
pg_df <- as.data.frame(pg)
```


vessel groups 
```{r}
vgroups <- read_csv(here('project-dat','vessel_groups','k4_NaNspeedfilter_2014clusterYR_byArea_noncon-group-key.csv')) %>%
  filter(crab_year %in% keep_years)
str(vgroups)
vgroups_summary <- vgroups %>% 
  dplyr::select(subgroup,group_area,vessel_size,crab_year) %>% distinct() %>%
  arrange(subgroup)
```


90% Utilization Distributions, as rasters, saved into a list of lists. A list of rasters (by year) was saved for each vessel group from script `04b_vessel_group_overlap.Rmd`
```{r}
udlist <- list()
for(i in seq(1,length(unique(vgroups_summary$subgroup)))){
  g <- unique(vgroups_summary$subgroup)[i]
  tmpuds <- readRDS(here(indir,paste0(g,"_",p,"ud_SpatialPolygonsGetVerticesHR_250grid_", keep_years[1],"-",substr(tail(keep_years,1),3,4), "crabYrs.rds")))
  # 
  # # set confidential years to null
  # g_keep_yrs <- vgroups_summary %>% filter(subgroup==g) %>% pull(crab_year)
  # to_remove <- which(!(names(tmpras) %in% g_keep_yrs))
  # if(length(to_remove) > 0){tmpras[to_remove] <- NULL}
  # 
  # # put in a place holder if years are missing
  # to_add <- keep_years[which(!(keep_years %in% names(tmpras)))]
  # if(length(to_add) > 0){
  #   start <- length(tmpras)
  #   for(j in seq(1,length(to_add))){
  #     tmpras[[(start+j)]] <- NA
  #     names(tmpras)[start+j] <- to_add[j]
      # }
  # }
  
  # add to list of lists
  udlist[[i]] <- tmpuds
}

names(udlist) <- unique(vgroups_summary$subgroup)
```
<br>


Check to make sure that the correct objects were read in above.
```{r}
n_uds <- udlist$`1-small`
c_uds <- udlist$`2-small`
y=2013

ggplot() +
      geom_polygon(data=states_geo_df, aes(x=long, y=lat, group=group), fill="grey87",linetype=1) +
      geom_point(data=pg_df, aes(x=Lon,y=Lat), color="black") +
  geom_polygon(data=n_uds, aes(x=long,y=lat, group=group))
  
```



```{r}
key_filter <- filter(vgroups_summary, subgroup %in% c("1-small","2-small"))

north_uds <- udlist[["1-small"]]
central_uds <- udlist[["2-small"]]

map_fishing_stacked <- function(north_uds,central_uds,key,keep_years,states_df_coast,label_year=TRUE){
  
  
  
}
  
  # prep to add to map
  ncol=pnw_palette("Bay",n=5)[1]
  ccol=pnw_palette("Bay",n=5)[4]
  
  myplot_sm <- ggplot()
  j = 0
  for(i in seq(1,length(keep_years))){
  yr <- as.numeric(keep_years[i])
  n_uds <- north_uds[north_uds$id==yr,]
  c_uds <- central_uds[central_uds$id==yr,]
  new_coast <- states_df_coast
    if(i > 1){
      n_uds <- fortify(n_uds) %>% mutate(long=long+j)
      c_uds <- fortify(c_uds) %>% mutate(long=long+j)
      new_coast <- new_coast %>% mutate(long=long+j)
    } 
    if(i < length(keep_years)){
      myplot_sm <- myplot_sm  +
        geom_path(data=new_coast,aes(x=long,y=lat,group=group),col="grey50") +
        geom_segment(aes(y=38.79, yend=38.79,x=-124,xend=-120), lty=3) +
        geom_polygon(data=n_uds, aes(x=long,y=lat, group=group), fill=ncol,color=ncol,alpha=0.3, size=0.5) +
        geom_polygon(data=fortify(c_uds), aes(x=long,y=lat, group=group), fill=ccol,color=ccol,alpha=0.3, size=0.5)
      j = j + offset
    } else{
    myplot_sm <- myplot_sm  +
      geom_polygon(data=states_geo_df, aes(x=long+j, y=lat, group=group), fill="grey87",linetype=1) +
      geom_path(data=new_coast,aes(x=long,y=lat,group=group),col="grey50") +
    geom_point(data=pg_df, aes(x=Lon+j,y=Lat), color="black") +
      geom_segment(aes(y=38.79, yend=38.79,x=-124,xend=-120+j), lty=3) +
      geom_polygon(data=n_uds, aes(x=long,y=lat, group=group), fill=ncol,color=ncol,alpha=0.3, size=0.5) +
      geom_polygon(data=fortify(c_uds), aes(x=long,y=lat, group=group), fill=ccol,color=ccol,alpha=0.3, size=0.5) +
      geom_text(data=pg_df, aes(x=Lon+j, y=Lat, label=port_group),size=pg_label_size,
                nudge_x=c(1.5,1.3,1.7,1,1.1,1),nudge_y=c(0.25,rep(0,5)))
    }
  }
  
  # finalize plot area / theme
  myplot_sm <- myplot_sm + theme_void() +
    theme(legend.position="none",plot.margin=margin(l=0,r=0.5,unit="cm"),
                         plot.title = element_text(hjust=0.5))  +
        coord_fixed(xlim=c(-127,-120+j),ylim=c(33,43))
  
  if(label_year){
    # data frame to label crab years
    nyrs <- length(keep_years)
    yrs_labels <- data.frame(yr = seq(as.numeric(first(keep_years)),as.numeric(last(keep_years)))) %>%
      mutate(ymin=42.5,ymax=42.5) %>%
      mutate(xmin=seq(-124, -124+((nyrs-1)*offset), by=offset),
             xmax=xmin)
    for(i in seq(1,nyrs)){
      myplot_sm <- myplot_sm +  annotation_custom(grob = textGrob(label = yrs_labels$yr[i], hjust = 0, gp = gpar(cex = 1.2)),
                                            ymin = yrs_labels$ymin[i], ymax = yrs_labels$ymax[i],
                                            xmin = yrs_labels$xmin[i], xmax = yrs_labels$xmax[i])
    }
  } #end if(label_year)
```


```{r}
png(here::here('project-dat','figures',"change_90ud_annual_SmLocal_byRegion_stacked.png"),height=500, width=700)
myplot_sm
dev.off()
```

```{r}
key_filter <- filter(vgroups_summary, subgroup %in% c("1-large","2-large"))

north_uds <- udlist[["1-large"]]
central_uds <- udlist[["2-large"]]

# map_fishing_stacked <- function(north_uds,central_uds,key,keep_years,states_df_coast,label_year=TRUE){
#   
#   
#   
# }
  
  # prep to add to map
  ncol=pnw_palette("Bay",n=5)[1]
  ccol=pnw_palette("Bay",n=5)[4]
  
  myplot_lg <- ggplot()
  j = 0
  for(i in seq(1,length(keep_years))){
  yr <- as.numeric(keep_years[i])
  n_uds <- north_uds[north_uds$id==yr,]
  c_uds <- central_uds[central_uds$id==yr,]
  new_coast <- states_df_coast
    if(i > 1){
      n_uds <- fortify(n_uds) %>% mutate(long=long+j)
      c_uds <- fortify(c_uds) %>% mutate(long=long+j)
      new_coast <- new_coast %>% mutate(long=long+j)
    } 
    if(i < length(keep_years)){
      myplot_lg <- myplot_lg  +
        geom_path(data=new_coast,aes(x=long,y=lat,group=group),col="grey50") +
        geom_segment(aes(y=38.79, yend=38.79,x=-124,xend=-120), lty=3) +
        geom_polygon(data=n_uds, aes(x=long,y=lat, group=group), fill=ncol,color=ncol,alpha=0.3, size=0.5) +
        geom_polygon(data=fortify(c_uds), aes(x=long,y=lat, group=group), fill=ccol,color=ccol,alpha=0.3, size=0.5)
      j = j + offset
    } else{
    myplot_lg <- myplot_lg  +
      geom_polygon(data=states_geo_df, aes(x=long+j, y=lat, group=group), fill="grey87",linetype=1) +
      geom_path(data=new_coast,aes(x=long,y=lat,group=group),col="grey50") +
    geom_point(data=pg_df, aes(x=Lon+j,y=Lat), color="black") +
      geom_segment(aes(y=38.79, yend=38.79,x=-124,xend=-120+j), lty=3) +
      geom_polygon(data=n_uds, aes(x=long,y=lat, group=group), fill=ncol,color=ncol,alpha=0.3, size=0.5) +
      geom_polygon(data=fortify(c_uds), aes(x=long,y=lat, group=group), fill=ccol,color=ccol,alpha=0.3, size=0.5) +
      geom_text(data=pg_df, aes(x=Lon+j, y=Lat, label=port_group),size=pg_label_size,
                nudge_x=c(1.5,1.3,1.7,1,1.1,1),nudge_y=c(0.25,rep(0,5)))
    }
  }
  
  # finalize plot area / theme
  myplot_lg <- myplot_lg + theme_void() +
    theme(legend.position="none",plot.margin=margin(l=0,r=0.5,unit="cm"),
                         plot.title = element_text(hjust=0.5))  +
        coord_fixed(xlim=c(-127,-120+j),ylim=c(33,43))
  
  if(label_year){
    # data frame to label crab years
    nyrs <- length(keep_years)
    yrs_labels <- data.frame(yr = seq(as.numeric(first(keep_years)),as.numeric(last(keep_years)))) %>%
      mutate(ymin=42.5,ymax=42.5) %>%
      mutate(xmin=seq(-124, -124+((nyrs-1)*offset), by=offset),
             xmax=xmin)
    for(i in seq(1,nyrs)){
      myplot_lg <- myplot_lg +  annotation_custom(grob = textGrob(label = yrs_labels$yr[i], hjust = 0, gp = gpar(cex = 1.2)),
                                            ymin = yrs_labels$ymin[i], ymax = yrs_labels$ymax[i],
                                            xmin = yrs_labels$xmin[i], xmax = yrs_labels$xmax[i])
    }
  } #end if(label_year)
```

```{r}
png(here::here('project-dat','figures',"change_90ud_annual_LgLocal_byRegion_stacked.png"),height=500, width=700)
myplot_lg
dev.off()
```




```{r}
key_filter <- filter(vgroups_summary, subgroup %in% c("5-large"))

north_uds <- udlist[["5-large"]]
# map_fishing_stacked <- function(north_uds,central_uds,key,keep_years,states_df_coast,label_year=TRUE){
#   
#   
#   
# }
  
  # prep to add to map
  ncol=pnw_palette("Moth",n=7)[4]
  
  myplot_coast <- ggplot()
  j = 0
  for(i in seq(1,length(keep_years))){
  yr <- as.numeric(keep_years[i])
  n_uds <- north_uds[north_uds$id==yr,]
  new_coast <- states_df_coast
    if(i > 1){
      n_uds <- fortify(n_uds) %>% mutate(long=long+j)
      new_coast <- new_coast %>% mutate(long=long+j)
    } 
    if(i < length(keep_years)){
      myplot_coast <- myplot_coast  +
        geom_path(data=new_coast,aes(x=long,y=lat,group=group),col="grey50") +
        geom_segment(aes(y=38.79, yend=38.79,x=-124,xend=-120), lty=3) +
        geom_polygon(data=n_uds, aes(x=long,y=lat, group=group), fill=ncol,color=ncol,alpha=0.3, size=0.5)
      j = j + offset
    } else{
    myplot_coast <- myplot_coast  +
      geom_polygon(data=states_geo_df, aes(x=long+j, y=lat, group=group), fill="grey87",linetype=1) +
      geom_path(data=new_coast,aes(x=long,y=lat,group=group),col="grey50") +
    geom_point(data=pg_df, aes(x=Lon+j,y=Lat), color="black") +
      geom_segment(aes(y=38.79, yend=38.79,x=-124,xend=-120+j), lty=3) +
      geom_polygon(data=n_uds, aes(x=long,y=lat, group=group), fill=ncol,color=ncol,alpha=0.3, size=0.5) +
      geom_text(data=pg_df, aes(x=Lon+j, y=Lat, label=port_group),size=pg_label_size,
                nudge_x=c(1.5,1.3,1.7,1,1.1,1),nudge_y=c(0.25,rep(0,5)))
    }
  }
  
  # finalize plot area / theme
  myplot_coast <- myplot_coast + theme_void() +
    theme(legend.position="none",plot.margin=margin(l=0,r=0.5,unit="cm"),
                         plot.title = element_text(hjust=0.5))  +
        coord_fixed(xlim=c(-127,-120+j),ylim=c(33,43))
  
  if(label_year){
    # data frame to label crab years
    nyrs <- length(keep_years)
    yrs_labels <- data.frame(yr = seq(as.numeric(first(keep_years)),as.numeric(last(keep_years)))) %>%
      mutate(ymin=42.5,ymax=42.5) %>%
      mutate(xmin=seq(-124, -124+((nyrs-1)*offset), by=offset),
             xmax=xmin)
    for(i in seq(1,nyrs)){
      myplot_coast <- myplot_coast +  annotation_custom(grob = textGrob(label = yrs_labels$yr[i], hjust = 0, gp = gpar(cex = 1.2)),
                                            ymin = yrs_labels$ymin[i], ymax = yrs_labels$ymax[i],
                                            xmin = yrs_labels$xmin[i], xmax = yrs_labels$xmax[i])
    }
  } #end if(label_year)
```


```{r}
png(here::here('project-dat','figures',"change_90ud_annual_All_byRegion_stacked.png"),res=200,height=2000, width=1800)
grid.arrange(grobs=list(myplot_sm,myplot_lg,myplot_coast),nrow=3)
dev.off()
```



