---
title: "Pre-Process 2019"
author: "Owen Liu"
date: "12/12/2019"
output: html_document
---

# Purpose

Import and join together all months' VMS data for 2019. We import each separate month's .csv file and then bind them together. Then, we rename column headers to match other years.

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(magrittr)
```

## Import and Bind Rows

We read date-times as character for now

```{r import2019}
mths <- c("Jan","Feb","March","April","May","June","July","Aug","Sept","Oct","Nov","Dec")
all2019<-purrr::map_df(mths,function(x){
  read_csv(here::here('data','raw','vms',paste0(x,"_2019.csv")),col_types = 'ccccddddddc')
})
glimpse(all2019)
```


## Fix Column Names and Reorder

We choose only some columns for now, to match the VMs data we have for other years.

```{r}
# use 2012 data as template
correct_colnames <- read_csv(here::here('data','raw','vms',paste0("VMS_all_data_2012.csv")),col_types='cddcddcc',n_max = 5) %>% colnames()
correct_colnames

all2019 <- all2019 %>% 
  select(`UTC time`,Lat, Lon, Name, `Avg Speed`, `Avg Course`, Docnum, `Declaration Code`) %>% 
  set_colnames(correct_colnames)

glimpse(all2019)
```

## Save Output

```{r}
write_csv(all2019,path = here::here('data','raw','vms','VMS_all_data_2019.csv'))
```
